/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cine.bd.pkg2.pkg0;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.ResultSet;
import java.sql.ResultSetMetaData;
import java.sql.SQLException;
import java.sql.Statement;
import java.util.logging.Level;
import java.util.logging.Logger;
import javax.swing.JOptionPane;
import javax.swing.table.DefaultTableModel;

/**
 *
 * @author Osiel Treto
 */
public class Cartelera extends javax.swing.JFrame {

    Connection conex = null;
    private static Connection Conexion;

    /**
     * Creates new form Cartelera
     */
    public Cartelera() {
        MySQLConnection();
        initComponents();
        mostrar();
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        BTNVENTA = new javax.swing.JButton();
        BTNHORARIO = new javax.swing.JButton();
        BTNCARTELERA = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        BTNSALIR = new javax.swing.JButton();
        BTNUSUARIO = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel5 = new javax.swing.JPanel();
        btnModificar = new javax.swing.JButton();
        btnEliminar = new javax.swing.JButton();
        btnRegistrar = new javax.swing.JButton();
        jPanel6 = new javax.swing.JPanel();
        jLabel4 = new javax.swing.JLabel();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        tCartelera = new javax.swing.JTable();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1000, 700));
        setResizable(false);
        setSize(new java.awt.Dimension(1000, 700));
        getContentPane().setLayout(null);

        jPanel3.setBackground(new java.awt.Color(51, 51, 51));
        jPanel3.setPreferredSize(new java.awt.Dimension(1000, 700));

        jPanel1.setBackground(new java.awt.Color(162, 28, 38));
        jPanel1.setAlignmentX(0.0F);
        jPanel1.setAlignmentY(0.0F);
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.setPreferredSize(new java.awt.Dimension(1000, 40));
        jPanel1.setLayout(null);

        BTNVENTA.setBackground(new java.awt.Color(162, 28, 38));
        BTNVENTA.setFont(new java.awt.Font("Haettenschweiler", 0, 30)); // NOI18N
        BTNVENTA.setForeground(new java.awt.Color(255, 255, 255));
        BTNVENTA.setText("Venta de Boletos");
        BTNVENTA.setAutoscrolls(true);
        BTNVENTA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNVENTAActionPerformed(evt);
            }
        });
        jPanel1.add(BTNVENTA);
        BTNVENTA.setBounds(200, 0, 200, 40);

        BTNHORARIO.setBackground(new java.awt.Color(162, 28, 38));
        BTNHORARIO.setFont(new java.awt.Font("Haettenschweiler", 0, 30)); // NOI18N
        BTNHORARIO.setForeground(new java.awt.Color(255, 255, 255));
        BTNHORARIO.setText("Horario");
        BTNHORARIO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNHORARIOActionPerformed(evt);
            }
        });
        jPanel1.add(BTNHORARIO);
        BTNHORARIO.setBounds(600, 0, 200, 40);

        BTNCARTELERA.setBackground(new java.awt.Color(162, 28, 38));
        BTNCARTELERA.setFont(new java.awt.Font("Haettenschweiler", 0, 30)); // NOI18N
        BTNCARTELERA.setForeground(new java.awt.Color(255, 255, 255));
        BTNCARTELERA.setText("Cartelera");
        BTNCARTELERA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNCARTELERAActionPerformed(evt);
            }
        });
        jPanel1.add(BTNCARTELERA);
        BTNCARTELERA.setBounds(400, 0, 200, 40);

        jLabel1.setFont(new java.awt.Font("Haettenschweiler", 0, 100)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Cine");

        jLabel2.setFont(new java.awt.Font("Haettenschweiler", 0, 100)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(162, 28, 38));
        jLabel2.setText("Planet");

        BTNSALIR.setBackground(new java.awt.Color(51, 51, 51));
        BTNSALIR.setFont(new java.awt.Font("Haettenschweiler", 0, 21)); // NOI18N
        BTNSALIR.setForeground(new java.awt.Color(255, 255, 255));
        BTNSALIR.setText("Salir");
        BTNSALIR.setBorderPainted(false);
        BTNSALIR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNSALIRActionPerformed(evt);
            }
        });

        BTNUSUARIO.setBackground(new java.awt.Color(51, 51, 51));
        BTNUSUARIO.setFont(new java.awt.Font("Haettenschweiler", 0, 21)); // NOI18N
        BTNUSUARIO.setForeground(new java.awt.Color(255, 255, 255));
        BTNUSUARIO.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/usuario.png"))); // NOI18N
        BTNUSUARIO.setText("Usuario");
        BTNUSUARIO.setBorderPainted(false);
        BTNUSUARIO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNUSUARIOActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(BTNSALIR, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(230, 230, 230)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BTNUSUARIO)
                .addGap(45, 45, 45))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addComponent(BTNSALIR, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel1)
                                .addComponent(jLabel2)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(BTNUSUARIO, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)))
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(69, 69, 69))
        );

        getContentPane().add(jPanel3);
        jPanel3.setBounds(0, 0, 1000, 155);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setLayout(null);

        jPanel5.setBackground(new java.awt.Color(239, 239, 239));

        btnModificar.setBackground(new java.awt.Color(255, 255, 255));
        btnModificar.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btnModificar.setForeground(new java.awt.Color(112, 112, 115));
        btnModificar.setText("Modificar");
        btnModificar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnModificarActionPerformed(evt);
            }
        });

        btnEliminar.setBackground(new java.awt.Color(255, 255, 255));
        btnEliminar.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btnEliminar.setForeground(new java.awt.Color(112, 112, 115));
        btnEliminar.setText("Eliminar");
        btnEliminar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnEliminarActionPerformed(evt);
            }
        });

        btnRegistrar.setBackground(new java.awt.Color(255, 255, 255));
        btnRegistrar.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        btnRegistrar.setForeground(new java.awt.Color(112, 112, 115));
        btnRegistrar.setText("Registrar");
        btnRegistrar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnRegistrarActionPerformed(evt);
            }
        });

        jPanel6.setBackground(new java.awt.Color(112, 112, 115));

        jLabel4.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        jLabel4.setForeground(new java.awt.Color(255, 255, 255));
        jLabel4.setText("OPCIONES");

        javax.swing.GroupLayout jPanel6Layout = new javax.swing.GroupLayout(jPanel6);
        jPanel6.setLayout(jPanel6Layout);
        jPanel6Layout.setHorizontalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel6Layout.createSequentialGroup()
                .addGap(43, 43, 43)
                .addComponent(jLabel4)
                .addContainerGap(javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
        );
        jPanel6Layout.setVerticalGroup(
            jPanel6Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel4, javax.swing.GroupLayout.DEFAULT_SIZE, 41, Short.MAX_VALUE)
        );

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jPanel6, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(18, 18, 18)
                .addGroup(jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.TRAILING)
                    .addComponent(btnModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE)
                    .addComponent(btnRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 120, javax.swing.GroupLayout.PREFERRED_SIZE))
                .addContainerGap(22, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel5Layout.createSequentialGroup()
                .addComponent(jPanel6, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnRegistrar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnEliminar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(18, 18, 18)
                .addComponent(btnModificar, javax.swing.GroupLayout.PREFERRED_SIZE, 30, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addContainerGap(25, Short.MAX_VALUE))
        );

        jPanel2.add(jPanel5);
        jPanel5.setBounds(20, 20, 160, 210);

        jPanel4.setBackground(new java.awt.Color(162, 28, 38));

        jLabel3.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Cartelera");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addContainerGap(312, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel4);
        jPanel4.setBounds(200, 20, 420, 40);

        tCartelera.setBackground(new java.awt.Color(51, 51, 51));
        tCartelera.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        tCartelera.setForeground(new java.awt.Color(255, 255, 255));
        tCartelera.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null},
                {null, null, null, null, null}
            },
            new String [] {
                "Titulo", "Director", "Año", "Clasificación", "Género"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.String.class, java.lang.Integer.class, java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false, false, false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        tCartelera.setEnabled(false);
        jScrollPane1.setViewportView(tCartelera);
        if (tCartelera.getColumnModel().getColumnCount() > 0) {
            tCartelera.getColumnModel().getColumn(0).setResizable(false);
            tCartelera.getColumnModel().getColumn(1).setResizable(false);
            tCartelera.getColumnModel().getColumn(2).setResizable(false);
            tCartelera.getColumnModel().getColumn(3).setResizable(false);
            tCartelera.getColumnModel().getColumn(4).setResizable(false);
        }

        jPanel2.add(jScrollPane1);
        jScrollPane1.setBounds(200, 80, 420, 350);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(180, 150, 640, 550);

        jLabel5.setBackground(new java.awt.Color(204, 102, 0));
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cartelera/Verdad O Reto.jpg"))); // NOI18N
        getContentPane().add(jLabel5);
        jLabel5.setBounds(0, 420, 182, 272);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cartelera/avengers.jpg"))); // NOI18N
        getContentPane().add(jLabel6);
        jLabel6.setBounds(0, 150, 182, 272);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cartelera/Rampage Devastación.jpg"))); // NOI18N
        getContentPane().add(jLabel8);
        jLabel8.setBounds(820, 150, 182, 272);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cartelera/deadpool.jpg"))); // NOI18N
        getContentPane().add(jLabel9);
        jLabel9.setBounds(820, 420, 182, 272);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnRegistrarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnRegistrarActionPerformed
        CarteleraRegistrar registrar = new CarteleraRegistrar();
        setVisible(false);
        registrar.setVisible(true);
// TODO add your handling code here:
    }//GEN-LAST:event_btnRegistrarActionPerformed

    private void btnEliminarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnEliminarActionPerformed
        CarteleraEliminar eliminar = new CarteleraEliminar();
        setVisible(false);
        eliminar.setVisible(true);
// TODO add your handling code here:
    }//GEN-LAST:event_btnEliminarActionPerformed

    private void btnModificarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnModificarActionPerformed
        CarteleraModificar modificar = new CarteleraModificar();
        setVisible(false);
        modificar.setVisible(true);
// TODO add your handling code here:
    }//GEN-LAST:event_btnModificarActionPerformed

    private void BTNVENTAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNVENTAActionPerformed
        Venta venta2 = new Venta();
        setVisible(false);

        venta2.setVisible(true);

        // TODO add your handling code here:
    }//GEN-LAST:event_BTNVENTAActionPerformed

    private void BTNCARTELERAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNCARTELERAActionPerformed
        Cartelera cartelera2 = new Cartelera();
        setVisible(false);

        cartelera2.setVisible(true);

        // TODO add your handling code here:
    }//GEN-LAST:event_BTNCARTELERAActionPerformed

    private void BTNHORARIOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNHORARIOActionPerformed
        Horario horario2 = new Horario();
        setVisible(false);

        horario2.setVisible(true);

        // TODO add your handling code here:
    }//GEN-LAST:event_BTNHORARIOActionPerformed

    private void BTNSALIRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNSALIRActionPerformed
        try {
            Conexion.close();
            System.out.println("Se ha finalizado la conexión con el servidor");
            System.exit(0);

        } catch (SQLException ex) {
            Logger.getLogger(Usuario.class.getName()).log(Level.SEVERE, null, ex);
            System.out.println("Se ha finalizado la conexión con el servidor");
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_BTNSALIRActionPerformed

    private void BTNUSUARIOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNUSUARIOActionPerformed
        Usuario usuario5 = new Usuario();
        setVisible(false);
        usuario5.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_BTNUSUARIOActionPerformed

    /**
     * @param args the command line arguments
     */
    public void mostrar() {
        try {
            Conexion = DriverManager.getConnection("jdbc:mysql://localhost:3306/cine", "root", "");
            Statement sta = Conexion.createStatement();
            String sql = "SELECT * FROM cartelera;";
            DefaultTableModel modelo = new DefaultTableModel();
            ResultSet rst = sta.executeQuery(sql);
            ResultSetMetaData rsMd = rst.getMetaData();
            int numeroColumnas = rsMd.getColumnCount();
            this.tCartelera.setModel(modelo);
            for (int i = 1; i <= numeroColumnas ; i++) {
                modelo.addColumn(rsMd.getColumnLabel(i));
            }
            while (rst.next()) {
                Object[] fila = new Object[numeroColumnas];
                for (int i = 0; i < numeroColumnas; i++) {
                    fila[i] = rst.getObject(i + 1);
                }
                modelo.addRow(fila);
            }
            sta.close();
        } catch (SQLException ex) {
            JOptionPane.showMessageDialog(null, "Ha ocurrido un error " + ex);
        }
    }

    public void MySQLConnection() {
        try {
            Class.forName("com.mysql.jdbc.Driver");
            Conexion = DriverManager.getConnection("jdbc:mysql://localhost:3306/cine", "root", "");
            System.out.println("Se ha iniciado la conexión con el servidor de forma exitosa (Cartelera)");

        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Cartelera.class
                    .getName()).log(Level.SEVERE, null, ex);

        } catch (SQLException ex) {
            Logger.getLogger(Cartelera.class
                    .getName()).log(Level.SEVERE, null, ex);
        }
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(Cartelera.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(Cartelera.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(Cartelera.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(Cartelera.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new Cartelera().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTNCARTELERA;
    private javax.swing.JButton BTNHORARIO;
    private javax.swing.JButton BTNSALIR;
    private javax.swing.JButton BTNUSUARIO;
    private javax.swing.JButton BTNVENTA;
    private javax.swing.JButton btnEliminar;
    private javax.swing.JButton btnModificar;
    private javax.swing.JButton btnRegistrar;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel4;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable tCartelera;
    // End of variables declaration//GEN-END:variables
}
