/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package cine.bd.pkg2.pkg0;

import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.SQLException;
import java.util.logging.Level;
import java.util.logging.Logger;

/**
 *
 * @author OsielAlejandro
 */
public class VentaComprar extends javax.swing.JFrame {

    String nombre;
    String titulo;
    String horario;
    String sala;
    String asiento;

    public VentaComprar(String nombre, String titulo, String horario, String sala, String asiento) {
        this.nombre = nombre;
        this.titulo = titulo;
        this.horario = horario;
        this.sala = sala;
        this.asiento = asiento;
    }

    public String getNombre() {
        return nombre;
    }

    public void setNombre(String nombre) {
        this.nombre = nombre;
    }

    public String getTitulo() {
        return titulo;
    }

    public void setTitulo(String titulo) {
        this.titulo = titulo;
    }

    public String getHorario() {
        return horario;
    }

    public void setHorario(String horario) {
        this.horario = horario;
    }

    public String getSala() {
        return sala;
    }

    public void setSala(String sala) {
        this.sala = sala;
    }

    public String getAsiento() {
        return asiento;
    }

    public void setAsiento(String asiento) {
        this.asiento = asiento;
    }
    
    
    Connection conex = null;
    private static Connection Conexion;

    /**
     * Creates new form VentaComprar
     */
    public VentaComprar() {

        MySQLConnection();
        initComponents();
        LlenarComboBox();

    }

    public void LlenarComboBox() {
        
        System.out.println("\n "+nombre);
        System.out.println(titulo);
        System.out.println(horario);
        System.out.println(sala);
        System.out.println(asiento);
        
        cbAsiento.removeAllItems();

        for (int i = 1; i < 13; i++) {
            cbAsiento.addItem("A" + i);
        }
        for (int i = 1; i < 13; i++) {
            cbAsiento.addItem("B" + i);
        }
        for (int i = 1; i < 13; i++) {
            cbAsiento.addItem("C" + i);
        }
        for (int i = 1; i < 13; i++) {
            cbAsiento.addItem("D" + i);
        }
        for (int i = 1; i < 13; i++) {
            cbAsiento.addItem("E" + i);
        }
        for (int i = 1; i < 13; i++) {
            cbAsiento.addItem("F" + i);
        }

    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("unchecked")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jPanel3 = new javax.swing.JPanel();
        jPanel1 = new javax.swing.JPanel();
        BTNVENTA = new javax.swing.JButton();
        BTNCARTELERA = new javax.swing.JButton();
        BTNHORARIO = new javax.swing.JButton();
        jLabel1 = new javax.swing.JLabel();
        jLabel2 = new javax.swing.JLabel();
        BTNSALIR = new javax.swing.JButton();
        BTNUSUARIO = new javax.swing.JButton();
        jPanel2 = new javax.swing.JPanel();
        jPanel4 = new javax.swing.JPanel();
        jLabel3 = new javax.swing.JLabel();
        jPanel7 = new javax.swing.JPanel();
        btnAceptar = new javax.swing.JButton();
        jPanel8 = new javax.swing.JPanel();
        jLabel10 = new javax.swing.JLabel();
        jPanel9 = new javax.swing.JPanel();
        as1 = new javax.swing.JButton();
        as2 = new javax.swing.JButton();
        as3 = new javax.swing.JButton();
        as4 = new javax.swing.JButton();
        as5 = new javax.swing.JButton();
        jPanel5 = new javax.swing.JPanel();
        jLabel14 = new javax.swing.JLabel();
        as6 = new javax.swing.JButton();
        as7 = new javax.swing.JButton();
        as8 = new javax.swing.JButton();
        as9 = new javax.swing.JButton();
        as10 = new javax.swing.JButton();
        as11 = new javax.swing.JButton();
        as12 = new javax.swing.JButton();
        as13 = new javax.swing.JButton();
        as14 = new javax.swing.JButton();
        as15 = new javax.swing.JButton();
        as16 = new javax.swing.JButton();
        as17 = new javax.swing.JButton();
        as18 = new javax.swing.JButton();
        as19 = new javax.swing.JButton();
        as20 = new javax.swing.JButton();
        as21 = new javax.swing.JButton();
        as22 = new javax.swing.JButton();
        as23 = new javax.swing.JButton();
        as24 = new javax.swing.JButton();
        as25 = new javax.swing.JButton();
        as26 = new javax.swing.JButton();
        as27 = new javax.swing.JButton();
        as28 = new javax.swing.JButton();
        as29 = new javax.swing.JButton();
        as30 = new javax.swing.JButton();
        as31 = new javax.swing.JButton();
        as32 = new javax.swing.JButton();
        as33 = new javax.swing.JButton();
        as34 = new javax.swing.JButton();
        as35 = new javax.swing.JButton();
        as36 = new javax.swing.JButton();
        as37 = new javax.swing.JButton();
        as38 = new javax.swing.JButton();
        as39 = new javax.swing.JButton();
        as40 = new javax.swing.JButton();
        as41 = new javax.swing.JButton();
        as42 = new javax.swing.JButton();
        as43 = new javax.swing.JButton();
        as44 = new javax.swing.JButton();
        as45 = new javax.swing.JButton();
        as46 = new javax.swing.JButton();
        as47 = new javax.swing.JButton();
        as48 = new javax.swing.JButton();
        as49 = new javax.swing.JButton();
        as50 = new javax.swing.JButton();
        as51 = new javax.swing.JButton();
        as52 = new javax.swing.JButton();
        as53 = new javax.swing.JButton();
        as54 = new javax.swing.JButton();
        as55 = new javax.swing.JButton();
        as56 = new javax.swing.JButton();
        as57 = new javax.swing.JButton();
        as58 = new javax.swing.JButton();
        as59 = new javax.swing.JButton();
        as60 = new javax.swing.JButton();
        as61 = new javax.swing.JButton();
        as62 = new javax.swing.JButton();
        as63 = new javax.swing.JButton();
        as64 = new javax.swing.JButton();
        as65 = new javax.swing.JButton();
        as66 = new javax.swing.JButton();
        as67 = new javax.swing.JButton();
        as68 = new javax.swing.JButton();
        as69 = new javax.swing.JButton();
        as70 = new javax.swing.JButton();
        as71 = new javax.swing.JButton();
        as72 = new javax.swing.JButton();
        jLabel21 = new javax.swing.JLabel();
        jLabel22 = new javax.swing.JLabel();
        jLabel23 = new javax.swing.JLabel();
        jLabel24 = new javax.swing.JLabel();
        jLabel25 = new javax.swing.JLabel();
        jLabel26 = new javax.swing.JLabel();
        jLabel27 = new javax.swing.JLabel();
        jLabel28 = new javax.swing.JLabel();
        jLabel29 = new javax.swing.JLabel();
        jLabel30 = new javax.swing.JLabel();
        jLabel31 = new javax.swing.JLabel();
        jLabel32 = new javax.swing.JLabel();
        jLabel33 = new javax.swing.JLabel();
        jLabel34 = new javax.swing.JLabel();
        jLabel35 = new javax.swing.JLabel();
        jLabel36 = new javax.swing.JLabel();
        jLabel37 = new javax.swing.JLabel();
        jLabel38 = new javax.swing.JLabel();
        jLabel39 = new javax.swing.JLabel();
        jLabel11 = new javax.swing.JLabel();
        jLabel7 = new javax.swing.JLabel();
        jLabel13 = new javax.swing.JLabel();
        cbAsiento = new javax.swing.JComboBox<>();
        jLabel5 = new javax.swing.JLabel();
        jLabel6 = new javax.swing.JLabel();
        jLabel8 = new javax.swing.JLabel();
        jLabel9 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1000, 700));
        setResizable(false);
        setSize(new java.awt.Dimension(1000, 700));
        getContentPane().setLayout(null);

        jPanel3.setBackground(new java.awt.Color(51, 51, 51));
        jPanel3.setPreferredSize(new java.awt.Dimension(1000, 700));

        jPanel1.setBackground(new java.awt.Color(162, 28, 38));
        jPanel1.setAlignmentX(0.0F);
        jPanel1.setAlignmentY(0.0F);
        jPanel1.setCursor(new java.awt.Cursor(java.awt.Cursor.DEFAULT_CURSOR));
        jPanel1.setPreferredSize(new java.awt.Dimension(1000, 40));
        jPanel1.setLayout(null);

        BTNVENTA.setBackground(new java.awt.Color(162, 28, 38));
        BTNVENTA.setFont(new java.awt.Font("Haettenschweiler", 0, 30)); // NOI18N
        BTNVENTA.setForeground(new java.awt.Color(255, 255, 255));
        BTNVENTA.setText("Venta de Boletos");
        BTNVENTA.setAutoscrolls(true);
        BTNVENTA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNVENTAActionPerformed(evt);
            }
        });
        jPanel1.add(BTNVENTA);
        BTNVENTA.setBounds(200, 0, 200, 40);

        BTNCARTELERA.setBackground(new java.awt.Color(162, 28, 38));
        BTNCARTELERA.setFont(new java.awt.Font("Haettenschweiler", 0, 30)); // NOI18N
        BTNCARTELERA.setForeground(new java.awt.Color(255, 255, 255));
        BTNCARTELERA.setText("Cartelera");
        BTNCARTELERA.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNCARTELERAActionPerformed(evt);
            }
        });
        jPanel1.add(BTNCARTELERA);
        BTNCARTELERA.setBounds(400, 0, 200, 40);

        BTNHORARIO.setBackground(new java.awt.Color(162, 28, 38));
        BTNHORARIO.setFont(new java.awt.Font("Haettenschweiler", 0, 30)); // NOI18N
        BTNHORARIO.setForeground(new java.awt.Color(255, 255, 255));
        BTNHORARIO.setText("Horario");
        BTNHORARIO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNHORARIOActionPerformed(evt);
            }
        });
        jPanel1.add(BTNHORARIO);
        BTNHORARIO.setBounds(600, 0, 200, 40);

        jLabel1.setFont(new java.awt.Font("Haettenschweiler", 0, 100)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(255, 255, 255));
        jLabel1.setText("Cine");

        jLabel2.setFont(new java.awt.Font("Haettenschweiler", 0, 100)); // NOI18N
        jLabel2.setForeground(new java.awt.Color(162, 28, 38));
        jLabel2.setText("Planet");

        BTNSALIR.setBackground(new java.awt.Color(51, 51, 51));
        BTNSALIR.setFont(new java.awt.Font("Haettenschweiler", 0, 21)); // NOI18N
        BTNSALIR.setForeground(new java.awt.Color(255, 255, 255));
        BTNSALIR.setText("Salir");
        BTNSALIR.setBorderPainted(false);
        BTNSALIR.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNSALIRActionPerformed(evt);
            }
        });

        BTNUSUARIO.setBackground(new java.awt.Color(51, 51, 51));
        BTNUSUARIO.setFont(new java.awt.Font("Haettenschweiler", 0, 21)); // NOI18N
        BTNUSUARIO.setForeground(new java.awt.Color(255, 255, 255));
        BTNUSUARIO.setIcon(new javax.swing.ImageIcon(getClass().getResource("/img/usuario.png"))); // NOI18N
        BTNUSUARIO.setText("Usuario");
        BTNUSUARIO.setBorderPainted(false);
        BTNUSUARIO.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                BTNUSUARIOActionPerformed(evt);
            }
        });

        javax.swing.GroupLayout jPanel3Layout = new javax.swing.GroupLayout(jPanel3);
        jPanel3.setLayout(jPanel3Layout);
        jPanel3Layout.setHorizontalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGap(28, 28, 28)
                .addComponent(BTNSALIR, javax.swing.GroupLayout.PREFERRED_SIZE, 70, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(230, 230, 230)
                .addComponent(jLabel1)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.UNRELATED)
                .addComponent(jLabel2)
                .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
                .addComponent(BTNUSUARIO)
                .addGap(45, 45, 45))
            .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(0, 0, Short.MAX_VALUE))
        );
        jPanel3Layout.setVerticalGroup(
            jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel3Layout.createSequentialGroup()
                .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                    .addGroup(jPanel3Layout.createSequentialGroup()
                        .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
                            .addGroup(jPanel3Layout.createSequentialGroup()
                                .addGap(32, 32, 32)
                                .addComponent(BTNSALIR, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE))
                            .addGroup(jPanel3Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.BASELINE)
                                .addComponent(jLabel1)
                                .addComponent(jLabel2)))
                        .addPreferredGap(javax.swing.LayoutStyle.ComponentPlacement.RELATED, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE))
                    .addGroup(javax.swing.GroupLayout.Alignment.TRAILING, jPanel3Layout.createSequentialGroup()
                        .addGap(0, 0, Short.MAX_VALUE)
                        .addComponent(BTNUSUARIO, javax.swing.GroupLayout.PREFERRED_SIZE, 50, javax.swing.GroupLayout.PREFERRED_SIZE)
                        .addGap(30, 30, 30)))
                .addComponent(jPanel1, javax.swing.GroupLayout.PREFERRED_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.PREFERRED_SIZE)
                .addGap(69, 69, 69))
        );

        getContentPane().add(jPanel3);
        jPanel3.setBounds(0, 0, 1000, 155);

        jPanel2.setBackground(new java.awt.Color(255, 255, 255));
        jPanel2.setMinimumSize(new java.awt.Dimension(1000, 700));
        jPanel2.setLayout(null);

        jPanel4.setBackground(new java.awt.Color(162, 28, 38));

        jLabel3.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel3.setForeground(new java.awt.Color(255, 255, 255));
        jLabel3.setText("Venta de boletos");

        javax.swing.GroupLayout jPanel4Layout = new javax.swing.GroupLayout(jPanel4);
        jPanel4.setLayout(jPanel4Layout);
        jPanel4Layout.setHorizontalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel4Layout.createSequentialGroup()
                .addContainerGap()
                .addComponent(jLabel3)
                .addContainerGap(409, Short.MAX_VALUE))
        );
        jPanel4Layout.setVerticalGroup(
            jPanel4Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel3, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, 40, Short.MAX_VALUE)
        );

        jPanel2.add(jPanel4);
        jPanel4.setBounds(20, 20, 600, 40);

        jPanel7.setLayout(null);

        btnAceptar.setBackground(new java.awt.Color(162, 28, 38));
        btnAceptar.setFont(new java.awt.Font("Haettenschweiler", 0, 21)); // NOI18N
        btnAceptar.setForeground(new java.awt.Color(255, 255, 255));
        btnAceptar.setText("Aceptar");
        btnAceptar.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                btnAceptarActionPerformed(evt);
            }
        });
        jPanel7.add(btnAceptar);
        btnAceptar.setBounds(390, 380, 144, 39);

        jPanel8.setBackground(new java.awt.Color(112, 112, 115));
        jPanel8.setLayout(null);

        jLabel10.setFont(new java.awt.Font("Arial", 0, 24)); // NOI18N
        jLabel10.setForeground(new java.awt.Color(255, 255, 255));
        jLabel10.setText("Elija su asiento");
        jPanel8.add(jLabel10);
        jLabel10.setBounds(210, 0, 180, 40);

        jPanel7.add(jPanel8);
        jPanel8.setBounds(0, 0, 600, 40);

        jPanel9.setBackground(new java.awt.Color(255, 255, 255));
        jPanel9.setLayout(null);

        as1.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asiento/lib.png"))); // NOI18N
        as1.setBorderPainted(false);
        as1.setContentAreaFilled(false);
        as1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                as1ActionPerformed(evt);
            }
        });
        jPanel9.add(as1);
        as1.setBounds(40, 40, 30, 30);

        as2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asiento/lib.png"))); // NOI18N
        as2.setBorderPainted(false);
        as2.setContentAreaFilled(false);
        as2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                as2ActionPerformed(evt);
            }
        });
        jPanel9.add(as2);
        as2.setBounds(70, 40, 30, 30);

        as3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asiento/lib.png"))); // NOI18N
        as3.setBorderPainted(false);
        as3.setContentAreaFilled(false);
        as3.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                as3ActionPerformed(evt);
            }
        });
        jPanel9.add(as3);
        as3.setBounds(120, 40, 30, 30);

        as4.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asiento/lib.png"))); // NOI18N
        as4.setBorderPainted(false);
        as4.setContentAreaFilled(false);
        as4.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                as4ActionPerformed(evt);
            }
        });
        jPanel9.add(as4);
        as4.setBounds(150, 40, 30, 30);

        as5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asiento/lib.png"))); // NOI18N
        as5.setBorderPainted(false);
        as5.setContentAreaFilled(false);
        as5.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                as5ActionPerformed(evt);
            }
        });
        jPanel9.add(as5);
        as5.setBounds(180, 40, 30, 30);

        jPanel5.setBackground(new java.awt.Color(162, 28, 38));

        jLabel14.setFont(new java.awt.Font("Calibri", 0, 18)); // NOI18N
        jLabel14.setForeground(new java.awt.Color(255, 255, 255));
        jLabel14.setText("Pantalla");

        javax.swing.GroupLayout jPanel5Layout = new javax.swing.GroupLayout(jPanel5);
        jPanel5.setLayout(jPanel5Layout);
        jPanel5Layout.setHorizontalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addGroup(jPanel5Layout.createSequentialGroup()
                .addGap(146, 146, 146)
                .addComponent(jLabel14)
                .addContainerGap(145, Short.MAX_VALUE))
        );
        jPanel5Layout.setVerticalGroup(
            jPanel5Layout.createParallelGroup(javax.swing.GroupLayout.Alignment.LEADING)
            .addComponent(jLabel14, javax.swing.GroupLayout.Alignment.TRAILING, javax.swing.GroupLayout.DEFAULT_SIZE, javax.swing.GroupLayout.DEFAULT_SIZE, Short.MAX_VALUE)
        );

        jPanel9.add(jPanel5);
        jPanel5.setBounds(70, 240, 350, 20);

        as6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asiento/lib.png"))); // NOI18N
        as6.setBorderPainted(false);
        as6.setContentAreaFilled(false);
        as6.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                as6ActionPerformed(evt);
            }
        });
        jPanel9.add(as6);
        as6.setBounds(210, 40, 30, 30);

        as7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asiento/lib.png"))); // NOI18N
        as7.setBorderPainted(false);
        as7.setContentAreaFilled(false);
        as7.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                as7ActionPerformed(evt);
            }
        });
        jPanel9.add(as7);
        as7.setBounds(240, 40, 30, 30);

        as8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asiento/lib.png"))); // NOI18N
        as8.setBorderPainted(false);
        as8.setContentAreaFilled(false);
        as8.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                as8ActionPerformed(evt);
            }
        });
        jPanel9.add(as8);
        as8.setBounds(270, 40, 30, 30);

        as9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asiento/lib.png"))); // NOI18N
        as9.setBorderPainted(false);
        as9.setContentAreaFilled(false);
        as9.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                as9ActionPerformed(evt);
            }
        });
        jPanel9.add(as9);
        as9.setBounds(300, 40, 30, 30);

        as10.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asiento/lib.png"))); // NOI18N
        as10.setBorderPainted(false);
        as10.setContentAreaFilled(false);
        as10.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                as10ActionPerformed(evt);
            }
        });
        jPanel9.add(as10);
        as10.setBounds(330, 40, 30, 30);

        as11.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asiento/lib.png"))); // NOI18N
        as11.setBorderPainted(false);
        as11.setContentAreaFilled(false);
        as11.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                as11ActionPerformed(evt);
            }
        });
        jPanel9.add(as11);
        as11.setBounds(390, 40, 30, 30);

        as12.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asiento/lib.png"))); // NOI18N
        as12.setBorderPainted(false);
        as12.setContentAreaFilled(false);
        as12.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                as12ActionPerformed(evt);
            }
        });
        jPanel9.add(as12);
        as12.setBounds(420, 40, 30, 30);

        as13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asiento/lib.png"))); // NOI18N
        as13.setBorderPainted(false);
        as13.setContentAreaFilled(false);
        as13.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                as13ActionPerformed(evt);
            }
        });
        jPanel9.add(as13);
        as13.setBounds(40, 70, 30, 30);

        as14.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asiento/lib.png"))); // NOI18N
        as14.setBorderPainted(false);
        as14.setContentAreaFilled(false);
        as14.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                as14ActionPerformed(evt);
            }
        });
        jPanel9.add(as14);
        as14.setBounds(70, 70, 30, 30);

        as15.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asiento/lib.png"))); // NOI18N
        as15.setBorderPainted(false);
        as15.setContentAreaFilled(false);
        as15.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                as15ActionPerformed(evt);
            }
        });
        jPanel9.add(as15);
        as15.setBounds(120, 70, 30, 30);

        as16.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asiento/lib.png"))); // NOI18N
        as16.setBorderPainted(false);
        as16.setContentAreaFilled(false);
        as16.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                as16ActionPerformed(evt);
            }
        });
        jPanel9.add(as16);
        as16.setBounds(150, 70, 30, 30);

        as17.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asiento/lib.png"))); // NOI18N
        as17.setBorderPainted(false);
        as17.setContentAreaFilled(false);
        as17.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                as17ActionPerformed(evt);
            }
        });
        jPanel9.add(as17);
        as17.setBounds(180, 70, 30, 30);

        as18.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asiento/lib.png"))); // NOI18N
        as18.setBorderPainted(false);
        as18.setContentAreaFilled(false);
        as18.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                as18ActionPerformed(evt);
            }
        });
        jPanel9.add(as18);
        as18.setBounds(210, 70, 30, 30);

        as19.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asiento/lib.png"))); // NOI18N
        as19.setBorderPainted(false);
        as19.setContentAreaFilled(false);
        as19.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                as19ActionPerformed(evt);
            }
        });
        jPanel9.add(as19);
        as19.setBounds(240, 70, 30, 30);

        as20.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asiento/lib.png"))); // NOI18N
        as20.setBorderPainted(false);
        as20.setContentAreaFilled(false);
        as20.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                as20ActionPerformed(evt);
            }
        });
        jPanel9.add(as20);
        as20.setBounds(270, 70, 30, 30);

        as21.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asiento/lib.png"))); // NOI18N
        as21.setBorderPainted(false);
        as21.setContentAreaFilled(false);
        as21.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                as21ActionPerformed(evt);
            }
        });
        jPanel9.add(as21);
        as21.setBounds(300, 70, 30, 30);

        as22.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asiento/lib.png"))); // NOI18N
        as22.setBorderPainted(false);
        as22.setContentAreaFilled(false);
        as22.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                as22ActionPerformed(evt);
            }
        });
        jPanel9.add(as22);
        as22.setBounds(330, 70, 30, 30);

        as23.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asiento/lib.png"))); // NOI18N
        as23.setBorderPainted(false);
        as23.setContentAreaFilled(false);
        as23.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                as23ActionPerformed(evt);
            }
        });
        jPanel9.add(as23);
        as23.setBounds(390, 70, 30, 30);

        as24.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asiento/lib.png"))); // NOI18N
        as24.setBorderPainted(false);
        as24.setContentAreaFilled(false);
        as24.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                as24ActionPerformed(evt);
            }
        });
        jPanel9.add(as24);
        as24.setBounds(420, 70, 30, 30);

        as25.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asiento/lib.png"))); // NOI18N
        as25.setBorderPainted(false);
        as25.setContentAreaFilled(false);
        as25.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                as25ActionPerformed(evt);
            }
        });
        jPanel9.add(as25);
        as25.setBounds(40, 100, 30, 30);

        as26.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asiento/lib.png"))); // NOI18N
        as26.setBorderPainted(false);
        as26.setContentAreaFilled(false);
        as26.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                as26ActionPerformed(evt);
            }
        });
        jPanel9.add(as26);
        as26.setBounds(70, 100, 30, 30);

        as27.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asiento/lib.png"))); // NOI18N
        as27.setBorderPainted(false);
        as27.setContentAreaFilled(false);
        as27.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                as27ActionPerformed(evt);
            }
        });
        jPanel9.add(as27);
        as27.setBounds(120, 100, 30, 30);

        as28.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asiento/lib.png"))); // NOI18N
        as28.setBorderPainted(false);
        as28.setContentAreaFilled(false);
        as28.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                as28ActionPerformed(evt);
            }
        });
        jPanel9.add(as28);
        as28.setBounds(150, 100, 30, 30);

        as29.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asiento/lib.png"))); // NOI18N
        as29.setBorderPainted(false);
        as29.setContentAreaFilled(false);
        as29.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                as29ActionPerformed(evt);
            }
        });
        jPanel9.add(as29);
        as29.setBounds(180, 100, 30, 30);

        as30.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asiento/lib.png"))); // NOI18N
        as30.setBorderPainted(false);
        as30.setContentAreaFilled(false);
        as30.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                as30ActionPerformed(evt);
            }
        });
        jPanel9.add(as30);
        as30.setBounds(210, 100, 30, 30);

        as31.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asiento/lib.png"))); // NOI18N
        as31.setBorderPainted(false);
        as31.setContentAreaFilled(false);
        as31.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                as31ActionPerformed(evt);
            }
        });
        jPanel9.add(as31);
        as31.setBounds(240, 100, 30, 30);

        as32.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asiento/lib.png"))); // NOI18N
        as32.setBorderPainted(false);
        as32.setContentAreaFilled(false);
        as32.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                as32ActionPerformed(evt);
            }
        });
        jPanel9.add(as32);
        as32.setBounds(270, 100, 30, 30);

        as33.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asiento/lib.png"))); // NOI18N
        as33.setBorderPainted(false);
        as33.setContentAreaFilled(false);
        as33.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                as33ActionPerformed(evt);
            }
        });
        jPanel9.add(as33);
        as33.setBounds(300, 100, 30, 30);

        as34.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asiento/lib.png"))); // NOI18N
        as34.setBorderPainted(false);
        as34.setContentAreaFilled(false);
        as34.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                as34ActionPerformed(evt);
            }
        });
        jPanel9.add(as34);
        as34.setBounds(330, 100, 30, 30);

        as35.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asiento/lib.png"))); // NOI18N
        as35.setBorderPainted(false);
        as35.setContentAreaFilled(false);
        as35.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                as35ActionPerformed(evt);
            }
        });
        jPanel9.add(as35);
        as35.setBounds(390, 100, 30, 30);

        as36.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asiento/lib.png"))); // NOI18N
        as36.setBorderPainted(false);
        as36.setContentAreaFilled(false);
        as36.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                as36ActionPerformed(evt);
            }
        });
        jPanel9.add(as36);
        as36.setBounds(420, 100, 30, 30);

        as37.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asiento/lib.png"))); // NOI18N
        as37.setBorderPainted(false);
        as37.setContentAreaFilled(false);
        as37.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                as37ActionPerformed(evt);
            }
        });
        jPanel9.add(as37);
        as37.setBounds(40, 130, 30, 30);

        as38.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asiento/lib.png"))); // NOI18N
        as38.setBorderPainted(false);
        as38.setContentAreaFilled(false);
        as38.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                as38ActionPerformed(evt);
            }
        });
        jPanel9.add(as38);
        as38.setBounds(70, 130, 30, 30);

        as39.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asiento/lib.png"))); // NOI18N
        as39.setBorderPainted(false);
        as39.setContentAreaFilled(false);
        as39.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                as39ActionPerformed(evt);
            }
        });
        jPanel9.add(as39);
        as39.setBounds(120, 130, 30, 30);

        as40.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asiento/lib.png"))); // NOI18N
        as40.setBorderPainted(false);
        as40.setContentAreaFilled(false);
        as40.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                as40ActionPerformed(evt);
            }
        });
        jPanel9.add(as40);
        as40.setBounds(150, 130, 30, 30);

        as41.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asiento/lib.png"))); // NOI18N
        as41.setBorderPainted(false);
        as41.setContentAreaFilled(false);
        as41.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                as41ActionPerformed(evt);
            }
        });
        jPanel9.add(as41);
        as41.setBounds(180, 130, 30, 30);

        as42.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asiento/lib.png"))); // NOI18N
        as42.setBorderPainted(false);
        as42.setContentAreaFilled(false);
        as42.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                as42ActionPerformed(evt);
            }
        });
        jPanel9.add(as42);
        as42.setBounds(210, 130, 30, 30);

        as43.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asiento/lib.png"))); // NOI18N
        as43.setBorderPainted(false);
        as43.setContentAreaFilled(false);
        as43.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                as43ActionPerformed(evt);
            }
        });
        jPanel9.add(as43);
        as43.setBounds(240, 130, 30, 30);

        as44.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asiento/lib.png"))); // NOI18N
        as44.setBorderPainted(false);
        as44.setContentAreaFilled(false);
        as44.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                as44ActionPerformed(evt);
            }
        });
        jPanel9.add(as44);
        as44.setBounds(270, 130, 30, 30);

        as45.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asiento/lib.png"))); // NOI18N
        as45.setBorderPainted(false);
        as45.setContentAreaFilled(false);
        as45.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                as45ActionPerformed(evt);
            }
        });
        jPanel9.add(as45);
        as45.setBounds(300, 130, 30, 30);

        as46.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asiento/lib.png"))); // NOI18N
        as46.setBorderPainted(false);
        as46.setContentAreaFilled(false);
        as46.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                as46ActionPerformed(evt);
            }
        });
        jPanel9.add(as46);
        as46.setBounds(330, 130, 30, 30);

        as47.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asiento/lib.png"))); // NOI18N
        as47.setBorderPainted(false);
        as47.setContentAreaFilled(false);
        as47.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                as47ActionPerformed(evt);
            }
        });
        jPanel9.add(as47);
        as47.setBounds(390, 130, 30, 30);

        as48.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asiento/lib.png"))); // NOI18N
        as48.setBorderPainted(false);
        as48.setContentAreaFilled(false);
        as48.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                as48ActionPerformed(evt);
            }
        });
        jPanel9.add(as48);
        as48.setBounds(420, 130, 30, 30);

        as49.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asiento/lib.png"))); // NOI18N
        as49.setBorderPainted(false);
        as49.setContentAreaFilled(false);
        as49.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                as49ActionPerformed(evt);
            }
        });
        jPanel9.add(as49);
        as49.setBounds(40, 160, 30, 30);

        as50.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asiento/lib.png"))); // NOI18N
        as50.setBorderPainted(false);
        as50.setContentAreaFilled(false);
        as50.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                as50ActionPerformed(evt);
            }
        });
        jPanel9.add(as50);
        as50.setBounds(70, 160, 30, 30);

        as51.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asiento/lib.png"))); // NOI18N
        as51.setBorderPainted(false);
        as51.setContentAreaFilled(false);
        as51.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                as51ActionPerformed(evt);
            }
        });
        jPanel9.add(as51);
        as51.setBounds(120, 160, 30, 30);

        as52.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asiento/lib.png"))); // NOI18N
        as52.setBorderPainted(false);
        as52.setContentAreaFilled(false);
        as52.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                as52ActionPerformed(evt);
            }
        });
        jPanel9.add(as52);
        as52.setBounds(150, 160, 30, 30);

        as53.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asiento/lib.png"))); // NOI18N
        as53.setBorderPainted(false);
        as53.setContentAreaFilled(false);
        as53.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                as53ActionPerformed(evt);
            }
        });
        jPanel9.add(as53);
        as53.setBounds(180, 160, 30, 30);

        as54.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asiento/lib.png"))); // NOI18N
        as54.setBorderPainted(false);
        as54.setContentAreaFilled(false);
        as54.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                as54ActionPerformed(evt);
            }
        });
        jPanel9.add(as54);
        as54.setBounds(210, 160, 30, 30);

        as55.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asiento/lib.png"))); // NOI18N
        as55.setBorderPainted(false);
        as55.setContentAreaFilled(false);
        as55.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                as55ActionPerformed(evt);
            }
        });
        jPanel9.add(as55);
        as55.setBounds(240, 160, 30, 30);

        as56.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asiento/lib.png"))); // NOI18N
        as56.setBorderPainted(false);
        as56.setContentAreaFilled(false);
        as56.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                as56ActionPerformed(evt);
            }
        });
        jPanel9.add(as56);
        as56.setBounds(270, 160, 30, 30);

        as57.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asiento/lib.png"))); // NOI18N
        as57.setBorderPainted(false);
        as57.setContentAreaFilled(false);
        as57.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                as57ActionPerformed(evt);
            }
        });
        jPanel9.add(as57);
        as57.setBounds(300, 160, 30, 30);

        as58.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asiento/lib.png"))); // NOI18N
        as58.setBorderPainted(false);
        as58.setContentAreaFilled(false);
        as58.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                as58ActionPerformed(evt);
            }
        });
        jPanel9.add(as58);
        as58.setBounds(330, 160, 30, 30);

        as59.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asiento/lib.png"))); // NOI18N
        as59.setBorderPainted(false);
        as59.setContentAreaFilled(false);
        as59.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                as59ActionPerformed(evt);
            }
        });
        jPanel9.add(as59);
        as59.setBounds(390, 160, 30, 30);

        as60.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asiento/lib.png"))); // NOI18N
        as60.setBorderPainted(false);
        as60.setContentAreaFilled(false);
        as60.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                as60ActionPerformed(evt);
            }
        });
        jPanel9.add(as60);
        as60.setBounds(420, 160, 30, 30);

        as61.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asiento/lib.png"))); // NOI18N
        as61.setBorderPainted(false);
        as61.setContentAreaFilled(false);
        as61.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                as61ActionPerformed(evt);
            }
        });
        jPanel9.add(as61);
        as61.setBounds(40, 190, 30, 30);

        as62.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asiento/lib.png"))); // NOI18N
        as62.setBorderPainted(false);
        as62.setContentAreaFilled(false);
        as62.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                as62ActionPerformed(evt);
            }
        });
        jPanel9.add(as62);
        as62.setBounds(70, 190, 30, 30);

        as63.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asiento/lib.png"))); // NOI18N
        as63.setBorderPainted(false);
        as63.setContentAreaFilled(false);
        as63.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                as63ActionPerformed(evt);
            }
        });
        jPanel9.add(as63);
        as63.setBounds(120, 190, 30, 30);

        as64.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asiento/lib.png"))); // NOI18N
        as64.setBorderPainted(false);
        as64.setContentAreaFilled(false);
        as64.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                as64ActionPerformed(evt);
            }
        });
        jPanel9.add(as64);
        as64.setBounds(150, 190, 30, 30);

        as65.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asiento/lib.png"))); // NOI18N
        as65.setBorderPainted(false);
        as65.setContentAreaFilled(false);
        as65.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                as65ActionPerformed(evt);
            }
        });
        jPanel9.add(as65);
        as65.setBounds(180, 190, 30, 30);

        as66.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asiento/lib.png"))); // NOI18N
        as66.setBorderPainted(false);
        as66.setContentAreaFilled(false);
        as66.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                as66ActionPerformed(evt);
            }
        });
        jPanel9.add(as66);
        as66.setBounds(210, 190, 30, 30);

        as67.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asiento/lib.png"))); // NOI18N
        as67.setBorderPainted(false);
        as67.setContentAreaFilled(false);
        as67.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                as67ActionPerformed(evt);
            }
        });
        jPanel9.add(as67);
        as67.setBounds(240, 190, 30, 30);

        as68.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asiento/lib.png"))); // NOI18N
        as68.setBorderPainted(false);
        as68.setContentAreaFilled(false);
        as68.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                as68ActionPerformed(evt);
            }
        });
        jPanel9.add(as68);
        as68.setBounds(270, 190, 30, 30);

        as69.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asiento/lib.png"))); // NOI18N
        as69.setBorderPainted(false);
        as69.setContentAreaFilled(false);
        as69.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                as69ActionPerformed(evt);
            }
        });
        jPanel9.add(as69);
        as69.setBounds(300, 190, 30, 30);

        as70.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asiento/lib.png"))); // NOI18N
        as70.setBorderPainted(false);
        as70.setContentAreaFilled(false);
        as70.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                as70ActionPerformed(evt);
            }
        });
        jPanel9.add(as70);
        as70.setBounds(330, 190, 30, 30);

        as71.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asiento/lib.png"))); // NOI18N
        as71.setBorderPainted(false);
        as71.setContentAreaFilled(false);
        as71.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                as71ActionPerformed(evt);
            }
        });
        jPanel9.add(as71);
        as71.setBounds(390, 190, 30, 30);

        as72.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asiento/lib.png"))); // NOI18N
        as72.setBorderPainted(false);
        as72.setContentAreaFilled(false);
        as72.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                as72ActionPerformed(evt);
            }
        });
        jPanel9.add(as72);
        as72.setBounds(420, 190, 30, 30);

        jLabel21.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel21.setForeground(new java.awt.Color(162, 28, 38));
        jLabel21.setText("    F");
        jPanel9.add(jLabel21);
        jLabel21.setBounds(10, 190, 30, 30);

        jLabel22.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel22.setForeground(new java.awt.Color(162, 28, 38));
        jLabel22.setText("    1");
        jPanel9.add(jLabel22);
        jLabel22.setBounds(40, 10, 30, 30);

        jLabel23.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel23.setForeground(new java.awt.Color(162, 28, 38));
        jLabel23.setText("    2");
        jPanel9.add(jLabel23);
        jLabel23.setBounds(70, 10, 30, 30);

        jLabel24.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel24.setForeground(new java.awt.Color(162, 28, 38));
        jLabel24.setText("    3");
        jPanel9.add(jLabel24);
        jLabel24.setBounds(120, 10, 30, 30);

        jLabel25.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel25.setForeground(new java.awt.Color(162, 28, 38));
        jLabel25.setText("    4");
        jPanel9.add(jLabel25);
        jLabel25.setBounds(150, 10, 30, 30);

        jLabel26.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel26.setForeground(new java.awt.Color(162, 28, 38));
        jLabel26.setText("    5");
        jPanel9.add(jLabel26);
        jLabel26.setBounds(180, 10, 30, 30);

        jLabel27.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel27.setForeground(new java.awt.Color(162, 28, 38));
        jLabel27.setText("    6");
        jPanel9.add(jLabel27);
        jLabel27.setBounds(210, 10, 30, 30);

        jLabel28.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel28.setForeground(new java.awt.Color(162, 28, 38));
        jLabel28.setText("    7");
        jPanel9.add(jLabel28);
        jLabel28.setBounds(240, 10, 30, 30);

        jLabel29.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel29.setForeground(new java.awt.Color(162, 28, 38));
        jLabel29.setText("    8");
        jPanel9.add(jLabel29);
        jLabel29.setBounds(270, 10, 30, 30);

        jLabel30.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel30.setForeground(new java.awt.Color(162, 28, 38));
        jLabel30.setText("    9");
        jLabel30.setToolTipText("");
        jPanel9.add(jLabel30);
        jLabel30.setBounds(300, 10, 30, 30);

        jLabel31.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel31.setForeground(new java.awt.Color(162, 28, 38));
        jLabel31.setText("   10");
        jPanel9.add(jLabel31);
        jLabel31.setBounds(330, 10, 30, 30);

        jLabel32.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel32.setForeground(new java.awt.Color(162, 28, 38));
        jLabel32.setText("   11");
        jPanel9.add(jLabel32);
        jLabel32.setBounds(390, 10, 30, 30);

        jLabel33.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel33.setForeground(new java.awt.Color(162, 28, 38));
        jLabel33.setText("   12");
        jPanel9.add(jLabel33);
        jLabel33.setBounds(420, 10, 30, 30);

        jLabel34.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel34.setForeground(new java.awt.Color(162, 28, 38));
        jLabel34.setText("    A");
        jPanel9.add(jLabel34);
        jLabel34.setBounds(10, 40, 30, 30);

        jLabel35.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel35.setForeground(new java.awt.Color(162, 28, 38));
        jLabel35.setText("    B");
        jPanel9.add(jLabel35);
        jLabel35.setBounds(10, 70, 30, 30);

        jLabel36.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel36.setForeground(new java.awt.Color(162, 28, 38));
        jLabel36.setText("    C");
        jPanel9.add(jLabel36);
        jLabel36.setBounds(10, 100, 30, 30);

        jLabel37.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel37.setForeground(new java.awt.Color(162, 28, 38));
        jLabel37.setText("    D");
        jLabel37.setToolTipText("");
        jPanel9.add(jLabel37);
        jLabel37.setBounds(10, 130, 30, 30);

        jLabel38.setFont(new java.awt.Font("Calibri", 1, 14)); // NOI18N
        jLabel38.setForeground(new java.awt.Color(162, 28, 38));
        jLabel38.setText("    E");
        jPanel9.add(jLabel38);
        jLabel38.setBounds(10, 160, 30, 30);

        jLabel39.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel39.setText("    A");
        jPanel9.add(jLabel39);
        jLabel39.setBounds(10, 190, 30, 30);

        jPanel7.add(jPanel9);
        jPanel9.setBounds(70, 90, 460, 270);

        jLabel11.setFont(new java.awt.Font("Arial", 0, 18)); // NOI18N
        jLabel11.setText("Asiento");
        jPanel7.add(jLabel11);
        jLabel11.setBounds(70, 390, 70, 25);

        jLabel7.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel7.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asiento/lib.png"))); // NOI18N
        jLabel7.setText("Asiento libre");
        jPanel7.add(jLabel7);
        jLabel7.setBounds(130, 40, 150, 50);

        jLabel13.setFont(new java.awt.Font("Calibri", 0, 14)); // NOI18N
        jLabel13.setIcon(new javax.swing.ImageIcon(getClass().getResource("/asiento/ocu.png"))); // NOI18N
        jLabel13.setText("Asiento ocupado");
        jPanel7.add(jLabel13);
        jLabel13.setBounds(290, 40, 170, 50);

        cbAsiento.setBackground(new java.awt.Color(51, 51, 51));
        cbAsiento.setFont(new java.awt.Font("Arial", 0, 14)); // NOI18N
        cbAsiento.setForeground(new java.awt.Color(255, 255, 255));
        cbAsiento.setModel(new javax.swing.DefaultComboBoxModel<>(new String[] { "Item 1", "Item 2", "Item 3", "Item 4" }));
        cbAsiento.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                cbAsientoActionPerformed(evt);
            }
        });
        jPanel7.add(cbAsiento);
        cbAsiento.setBounds(160, 390, 60, 25);

        jPanel2.add(jPanel7);
        jPanel7.setBounds(20, 80, 600, 450);

        getContentPane().add(jPanel2);
        jPanel2.setBounds(180, 150, 640, 550);

        jLabel5.setBackground(new java.awt.Color(204, 102, 0));
        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cartelera/deadpool.jpg"))); // NOI18N
        getContentPane().add(jLabel5);
        jLabel5.setBounds(0, 420, 182, 272);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cartelera/Hombre Al Agua.jpg"))); // NOI18N
        getContentPane().add(jLabel6);
        jLabel6.setBounds(0, 150, 182, 272);

        jLabel8.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cartelera/avengers.jpg"))); // NOI18N
        getContentPane().add(jLabel8);
        jLabel8.setBounds(820, 150, 182, 272);

        jLabel9.setIcon(new javax.swing.ImageIcon(getClass().getResource("/cartelera/venom.jpg"))); // NOI18N
        getContentPane().add(jLabel9);
        jLabel9.setBounds(820, 420, 182, 272);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void btnAceptarActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_btnAceptarActionPerformed

    }//GEN-LAST:event_btnAceptarActionPerformed

    private void as1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_as1ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_as1ActionPerformed

    private void as2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_as2ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_as2ActionPerformed

    private void as3ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_as3ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_as3ActionPerformed

    private void as4ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_as4ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_as4ActionPerformed

    private void as5ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_as5ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_as5ActionPerformed

    private void as6ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_as6ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_as6ActionPerformed

    private void as7ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_as7ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_as7ActionPerformed

    private void as8ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_as8ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_as8ActionPerformed

    private void as9ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_as9ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_as9ActionPerformed

    private void as10ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_as10ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_as10ActionPerformed

    private void as11ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_as11ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_as11ActionPerformed

    private void as12ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_as12ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_as12ActionPerformed

    private void as13ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_as13ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_as13ActionPerformed

    private void as14ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_as14ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_as14ActionPerformed

    private void as15ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_as15ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_as15ActionPerformed

    private void as16ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_as16ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_as16ActionPerformed

    private void as17ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_as17ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_as17ActionPerformed

    private void as18ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_as18ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_as18ActionPerformed

    private void as19ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_as19ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_as19ActionPerformed

    private void as20ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_as20ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_as20ActionPerformed

    private void as21ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_as21ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_as21ActionPerformed

    private void as22ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_as22ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_as22ActionPerformed

    private void as23ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_as23ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_as23ActionPerformed

    private void as24ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_as24ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_as24ActionPerformed

    private void as25ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_as25ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_as25ActionPerformed

    private void as26ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_as26ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_as26ActionPerformed

    private void as27ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_as27ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_as27ActionPerformed

    private void as28ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_as28ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_as28ActionPerformed

    private void as29ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_as29ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_as29ActionPerformed

    private void as30ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_as30ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_as30ActionPerformed

    private void as31ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_as31ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_as31ActionPerformed

    private void as32ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_as32ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_as32ActionPerformed

    private void as33ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_as33ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_as33ActionPerformed

    private void as34ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_as34ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_as34ActionPerformed

    private void as35ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_as35ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_as35ActionPerformed

    private void as36ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_as36ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_as36ActionPerformed

    private void as37ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_as37ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_as37ActionPerformed

    private void as38ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_as38ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_as38ActionPerformed

    private void as39ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_as39ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_as39ActionPerformed

    private void as40ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_as40ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_as40ActionPerformed

    private void as41ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_as41ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_as41ActionPerformed

    private void as42ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_as42ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_as42ActionPerformed

    private void as43ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_as43ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_as43ActionPerformed

    private void as44ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_as44ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_as44ActionPerformed

    private void as45ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_as45ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_as45ActionPerformed

    private void as46ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_as46ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_as46ActionPerformed

    private void as47ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_as47ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_as47ActionPerformed

    private void as48ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_as48ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_as48ActionPerformed

    private void as49ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_as49ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_as49ActionPerformed

    private void as50ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_as50ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_as50ActionPerformed

    private void as51ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_as51ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_as51ActionPerformed

    private void as52ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_as52ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_as52ActionPerformed

    private void as53ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_as53ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_as53ActionPerformed

    private void as54ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_as54ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_as54ActionPerformed

    private void as55ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_as55ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_as55ActionPerformed

    private void as56ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_as56ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_as56ActionPerformed

    private void as57ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_as57ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_as57ActionPerformed

    private void as58ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_as58ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_as58ActionPerformed

    private void as59ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_as59ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_as59ActionPerformed

    private void as60ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_as60ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_as60ActionPerformed

    private void as61ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_as61ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_as61ActionPerformed

    private void as62ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_as62ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_as62ActionPerformed

    private void as63ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_as63ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_as63ActionPerformed

    private void as64ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_as64ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_as64ActionPerformed

    private void as65ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_as65ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_as65ActionPerformed

    private void as66ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_as66ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_as66ActionPerformed

    private void as67ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_as67ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_as67ActionPerformed

    private void as68ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_as68ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_as68ActionPerformed

    private void as69ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_as69ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_as69ActionPerformed

    private void as70ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_as70ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_as70ActionPerformed

    private void as71ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_as71ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_as71ActionPerformed

    private void as72ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_as72ActionPerformed
        // TODO add your handling code here:
    }//GEN-LAST:event_as72ActionPerformed

    private void cbAsientoActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_cbAsientoActionPerformed
        //tfTotal.setText("$ " + 45);

// TODO add your handling code here:
    }//GEN-LAST:event_cbAsientoActionPerformed

    private void BTNVENTAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNVENTAActionPerformed
        Venta venta2 = new Venta();
        setVisible(false);

        venta2.setVisible(true);

        // TODO add your handling code here:
    }//GEN-LAST:event_BTNVENTAActionPerformed

    private void BTNCARTELERAActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNCARTELERAActionPerformed
        Cartelera cartelera2 = new Cartelera();
        setVisible(false);

        cartelera2.setVisible(true);

        // TODO add your handling code here:
    }//GEN-LAST:event_BTNCARTELERAActionPerformed

    private void BTNHORARIOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNHORARIOActionPerformed
        Horario horario2 = new Horario();
        setVisible(false);

        horario2.setVisible(true);

        // TODO add your handling code here:
    }//GEN-LAST:event_BTNHORARIOActionPerformed

    private void BTNSALIRActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNSALIRActionPerformed
        try {
            Conexion.close();
            System.out.println("Se ha finalizado la conexión con el servidor");
            System.exit(0);

        } catch (SQLException ex) {
            Logger.getLogger(Usuario.class.getName()).log(Level.SEVERE, null, ex);
            System.out.println("Se ha finalizado la conexión con el servidor");
        }

        // TODO add your handling code here:
    }//GEN-LAST:event_BTNSALIRActionPerformed

    private void BTNUSUARIOActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_BTNUSUARIOActionPerformed
        Usuario usuario5 = new Usuario();
        setVisible(false);
        usuario5.setVisible(true);
        // TODO add your handling code here:
    }//GEN-LAST:event_BTNUSUARIOActionPerformed

    /**
     * @param args the command line arguments
     */
    public void MySQLConnection() {
        try {
            Class.forName("com.mysql.jdbc.Driver");
            Conexion = DriverManager.getConnection("jdbc:mysql://localhost:3306/cine", "root", "");
            System.out.println("Se ha iniciado la conexión con el servidor de forma exitosa (Venta-Comprar)");

        } catch (ClassNotFoundException ex) {
            Logger.getLogger(Venta.class
                    .getName()).log(Level.SEVERE, null, ex);

        } catch (SQLException ex) {
            Logger.getLogger(Venta.class
                    .getName()).log(Level.SEVERE, null, ex);
        }
    }

    public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
        try {
            for (javax.swing.UIManager.LookAndFeelInfo info : javax.swing.UIManager.getInstalledLookAndFeels()) {
                if ("Nimbus".equals(info.getName())) {
                    javax.swing.UIManager.setLookAndFeel(info.getClassName());
                    break;
                }
            }
        } catch (ClassNotFoundException ex) {
            java.util.logging.Logger.getLogger(VentaComprar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (InstantiationException ex) {
            java.util.logging.Logger.getLogger(VentaComprar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (IllegalAccessException ex) {
            java.util.logging.Logger.getLogger(VentaComprar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        } catch (javax.swing.UnsupportedLookAndFeelException ex) {
            java.util.logging.Logger.getLogger(VentaComprar.class.getName()).log(java.util.logging.Level.SEVERE, null, ex);
        }
        //</editor-fold>

        /* Create and display the form */
        java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
                new VentaComprar().setVisible(true);
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton BTNCARTELERA;
    private javax.swing.JButton BTNHORARIO;
    private javax.swing.JButton BTNSALIR;
    private javax.swing.JButton BTNUSUARIO;
    private javax.swing.JButton BTNVENTA;
    private javax.swing.JButton as1;
    private javax.swing.JButton as10;
    private javax.swing.JButton as11;
    private javax.swing.JButton as12;
    private javax.swing.JButton as13;
    private javax.swing.JButton as14;
    private javax.swing.JButton as15;
    private javax.swing.JButton as16;
    private javax.swing.JButton as17;
    private javax.swing.JButton as18;
    private javax.swing.JButton as19;
    private javax.swing.JButton as2;
    private javax.swing.JButton as20;
    private javax.swing.JButton as21;
    private javax.swing.JButton as22;
    private javax.swing.JButton as23;
    private javax.swing.JButton as24;
    private javax.swing.JButton as25;
    private javax.swing.JButton as26;
    private javax.swing.JButton as27;
    private javax.swing.JButton as28;
    private javax.swing.JButton as29;
    private javax.swing.JButton as3;
    private javax.swing.JButton as30;
    private javax.swing.JButton as31;
    private javax.swing.JButton as32;
    private javax.swing.JButton as33;
    private javax.swing.JButton as34;
    private javax.swing.JButton as35;
    private javax.swing.JButton as36;
    private javax.swing.JButton as37;
    private javax.swing.JButton as38;
    private javax.swing.JButton as39;
    private javax.swing.JButton as4;
    private javax.swing.JButton as40;
    private javax.swing.JButton as41;
    private javax.swing.JButton as42;
    private javax.swing.JButton as43;
    private javax.swing.JButton as44;
    private javax.swing.JButton as45;
    private javax.swing.JButton as46;
    private javax.swing.JButton as47;
    private javax.swing.JButton as48;
    private javax.swing.JButton as49;
    private javax.swing.JButton as5;
    private javax.swing.JButton as50;
    private javax.swing.JButton as51;
    private javax.swing.JButton as52;
    private javax.swing.JButton as53;
    private javax.swing.JButton as54;
    private javax.swing.JButton as55;
    private javax.swing.JButton as56;
    private javax.swing.JButton as57;
    private javax.swing.JButton as58;
    private javax.swing.JButton as59;
    private javax.swing.JButton as6;
    private javax.swing.JButton as60;
    private javax.swing.JButton as61;
    private javax.swing.JButton as62;
    private javax.swing.JButton as63;
    private javax.swing.JButton as64;
    private javax.swing.JButton as65;
    private javax.swing.JButton as66;
    private javax.swing.JButton as67;
    private javax.swing.JButton as68;
    private javax.swing.JButton as69;
    private javax.swing.JButton as7;
    private javax.swing.JButton as70;
    private javax.swing.JButton as71;
    private javax.swing.JButton as72;
    private javax.swing.JButton as8;
    private javax.swing.JButton as9;
    private javax.swing.JButton btnAceptar;
    private javax.swing.JComboBox<String> cbAsiento;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel10;
    private javax.swing.JLabel jLabel11;
    private javax.swing.JLabel jLabel13;
    private javax.swing.JLabel jLabel14;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel21;
    private javax.swing.JLabel jLabel22;
    private javax.swing.JLabel jLabel23;
    private javax.swing.JLabel jLabel24;
    private javax.swing.JLabel jLabel25;
    private javax.swing.JLabel jLabel26;
    private javax.swing.JLabel jLabel27;
    private javax.swing.JLabel jLabel28;
    private javax.swing.JLabel jLabel29;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel30;
    private javax.swing.JLabel jLabel31;
    private javax.swing.JLabel jLabel32;
    private javax.swing.JLabel jLabel33;
    private javax.swing.JLabel jLabel34;
    private javax.swing.JLabel jLabel35;
    private javax.swing.JLabel jLabel36;
    private javax.swing.JLabel jLabel37;
    private javax.swing.JLabel jLabel38;
    private javax.swing.JLabel jLabel39;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JLabel jLabel7;
    private javax.swing.JLabel jLabel8;
    private javax.swing.JLabel jLabel9;
    private javax.swing.JPanel jPanel1;
    private javax.swing.JPanel jPanel2;
    private javax.swing.JPanel jPanel3;
    private javax.swing.JPanel jPanel4;
    private javax.swing.JPanel jPanel5;
    private javax.swing.JPanel jPanel7;
    private javax.swing.JPanel jPanel8;
    private javax.swing.JPanel jPanel9;
    // End of variables declaration//GEN-END:variables
}
